"""empty message

Revision ID: 0e65c2d86de0
Revises: bcb3fe981133
Create Date: 2018-03-14 16:52:39.702148

"""

# revision identifiers, used by Alembic.
revision = '0e65c2d86de0'
down_revision = 'bcb3fe981133'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
