"""empty message

Revision ID: 296be0fafd54
Revises: 6d54922dc685
Create Date: 2018-03-14 15:47:24.052158

"""

# revision identifiers, used by Alembic.
revision = '296be0fafd54'
down_revision = '6d54922dc685'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
