"""empty message

Revision ID: bcb3fe981133
Revises: 296be0fafd54
Create Date: 2018-03-14 16:51:15.834833

"""

# revision identifiers, used by Alembic.
revision = 'bcb3fe981133'
down_revision = '296be0fafd54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
